import "./globals.scss";
import type { Metadata } from "next";
import { ClientLayout } from "./ClientLayout";
import NavBar from "./components/NavBar/NavBar";
import { M_PLUS_1 } from "next/font/google";
import LineSvgAnimate from "./components/LineSvgAnimate/LineSvgAnimate";

const mplus = M_PLUS_1({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test Page Mehran",
  description: "Generated by create next app 13 for Test",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center ${mplus.className} justify-center `}
      >
        <LineSvgAnimate />
        <div className={"container"}>
          <NavBar />
          <ClientLayout>{children}</ClientLayout>
        </div>
      </body>
    </html>
  );
}
